"""
Claude Call 2 — Newsletter Generator.
Takes signals, ETF candidates, market data, and approved sources,
and produces a structured newsletter in Markdown.
"""
from dataclasses import dataclass
from datetime import datetime
from typing import List

import anthropic

from src.analysis.etf_ranker import ETFCandidate
from src.analysis.summarizer import SignalSet
from src.fetchers.market_fetcher import MarketData
from src.utils.logger import logger


DISCLAIMER = {
    "fr": (
        "**AVERTISSEMENT** : Ce newsletter est généré automatiquement par un système d'IA "
        "et ne constitue pas un conseil en investissement financier. Les performances passées "
        "ne préjugent pas des performances futures. Consultez un conseiller financier qualifié "
        "avant toute décision d'investissement. L'auteur ne détient aucune position dans les "
        "instruments mentionnés."
    ),
    "es": (
        "**AVISO**: Este newsletter es generado automáticamente por un sistema de IA "
        "y no constituye asesoramiento financiero. El rendimiento pasado no garantiza resultados futuros. "
        "Consulte un asesor financiero cualificado antes de invertir. "
        "El autor no tiene posiciones en los instrumentos mencionados."
    ),
    "en": (
        "**DISCLAIMER**: This newsletter is generated by an automated AI system and does not "
        "constitute financial advice. Past performance is not indicative of future results. "
        "Always consult a qualified financial advisor before making investment decisions. "
        "The author holds no position in any of the securities mentioned."
    ),
}

LANG_INTRO = {
    "fr": "Rédigez entièrement en français.",
    "es": "Redacte completamente en español.",
    "en": "Write entirely in English.",
}


@dataclass
class Newsletter:
    subject: str
    markdown_body: str
    plain_text_body: str
    date: str


def _fmt_pct(v) -> str:
    if v is None:
        return "N/A"
    sign = "+" if v >= 0 else ""
    return f"{sign}{v:.2f}%"


def _build_candidates_text(candidates: List[ETFCandidate]) -> str:
    lines = []
    for i, c in enumerate(candidates, 1):
        lines.append(
            f"{i}. {c.name} ({c.ticker_yahoo})\n"
            f"   ISIN: {c.isin} | Provider: {c.provider.upper()} | TER: {c.ter}%\n"
            f"   Category: {c.category} | Geography: {c.geography}\n"
            f"   Themes: {', '.join(c.themes)}\n"
            f"   Performance: 1W {_fmt_pct(c.change_1w)} | 1M {_fmt_pct(c.change_1m)} | 3M {_fmt_pct(c.change_3m)}\n"
            f"   Score: {c.score:.2f}\n"
        )
    return "\n".join(lines)


def _build_market_snapshot(market_data: MarketData) -> str:
    lines = []
    for name, idx in market_data.indices.items():
        lines.append(f"- {name}: {idx.price} (1S: {_fmt_pct(idx.change_1w)})")
    if market_data.vix:
        vix_level = "faible" if market_data.vix < 15 else ("modéré" if market_data.vix < 25 else "élevé")
        lines.append(f"- VIX: {market_data.vix} ({vix_level})")
    if market_data.eur_usd:
        lines.append(f"- EUR/USD: {market_data.eur_usd}")
    return "\n".join(lines)


class NewsletterGenerator:
    def __init__(self, api_key: str, model: str = "claude-sonnet-4-6"):
        self.client = anthropic.Anthropic(api_key=api_key)
        self.model = model

    def generate(
        self,
        signal_set: SignalSet,
        candidates: List[ETFCandidate],
        market_data: MarketData,
        language: str = "fr",
        frequency: str = "weekly",
    ) -> Newsletter:
        logger.info(f"Claude Call 2: generating newsletter ({language}, {len(candidates)} ETF candidates)...")

        today = datetime.now()
        date_str = today.strftime("%d %B %Y")
        freq_label = {"daily": "du jour", "weekly": "de la semaine", "monthly": "du mois"}.get(frequency, "")
        subject = f"Newsletter Financière — {freq_label} {date_str}"

        candidates_text = _build_candidates_text(candidates)
        market_snapshot = _build_market_snapshot(market_data)
        signals_text = "\n".join(
            f"- [{s.type}] {s.rationale} (géographies: {', '.join(s.geographies)})"
            for s in signal_set.signals
        )
        sources_text = "\n".join(f"- {url}" for url in signal_set.approved_sources)
        disclaimer = DISCLAIMER.get(language, DISCLAIMER["en"])
        lang_instruction = LANG_INTRO.get(language, LANG_INTRO["en"])

        prompt = f"""You are a financial advisor writing a newsletter for a private investor with a French PEA (Plan d'Épargne en Actions) at BoursoBank.

{lang_instruction}

Today: {date_str}

---
MACRO CONTEXT (already extracted):
{signal_set.raw_summary}

---
SIGNALS IDENTIFIED:
{signals_text}

---
MARKET SNAPSHOT:
{market_snapshot}

---
TOP ETF CANDIDATES (pre-selected based on signals):
{candidates_text}

---
APPROVED SOURCE URLS (you may ONLY cite these — do NOT invent any URL):
{sources_text}

---
Write a complete newsletter in Markdown with this exact structure:

# Newsletter Financière — {freq_label} {date_str}

## Résumé Exécutif
[2-3 paragraphs: current macro environment, key drivers this period]

## Signaux Géopolitiques & Macro
[Bullet list: 4-6 key events/signals with their market impact. Cite source URLs where relevant.]

## Top ETF Picks

[For each ETF, write a section like:]
### 1. [ETF Name] ([ticker])
**Rationale**: [1-2 sentences tied to the macro signals above]
**Performance**: 1S: X% | 1M: X% | 3M: X%
**TER**: X% | **ISIN**: XXXXXXX | **Provider**: [Amundi/iShares]
**Source**: [URL if relevant, from approved sources only]

[Repeat for each ETF candidate, ranked by conviction]

## Snapshot de Marché
{market_snapshot}

## Sources
[Numbered list of all approved_sources URLs you cited in this newsletter]

---
{disclaimer}

---
Rules:
- Only cite URLs from the APPROVED SOURCE URLS list above
- Do not invent, guess, or modify any URL
- If no relevant source URL exists for a point, omit the source link
- Keep each ETF rationale focused on the macro signals, not generic ETF descriptions
- Be direct and actionable
"""

        try:
            response = self.client.messages.create(
                model=self.model,
                max_tokens=3000,
                messages=[{"role": "user", "content": prompt}],
            )
            markdown_body = response.content[0].text.strip()
            plain_text = _markdown_to_plain(markdown_body)

            logger.info("Newsletter generated successfully")
            return Newsletter(
                subject=subject,
                markdown_body=markdown_body,
                plain_text_body=plain_text,
                date=date_str,
            )

        except Exception as e:
            logger.error(f"Newsletter generation failed: {e}")
            # Return a minimal fallback newsletter
            fallback = f"# Newsletter Financière — {date_str}\n\n*Erreur lors de la génération. Veuillez réessayer.*\n\n{disclaimer}"
            return Newsletter(
                subject=subject,
                markdown_body=fallback,
                plain_text_body=fallback,
                date=date_str,
            )


def _markdown_to_plain(text: str) -> str:
    """Minimal Markdown → plain text for WhatsApp."""
    import re
    text = re.sub(r"#{1,6}\s*", "", text)         # headers
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)  # bold
    text = re.sub(r"\*(.*?)\*", r"\1", text)       # italic
    text = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1: \2", text)  # links
    text = re.sub(r"---+", "─" * 30, text)        # horizontal rules
    return text
